### ISSUE TITLE
Add Assurance Metrics

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/aker#172]
We would like to better understand how well Aker is performing.  To enable this understanding we'd like to collect the following:

- the count of the number of devices put on the block list
- the count of the number of transitions between different blocking windows
- the count of the number of times the schedule is set
- the count of the number of times a schedule failed to decode
- the count of the number of times the md5 check as failed
- the current timezone as set by the schedule
- the timezone offset based on the timezone applied to the schedule
- the time the process started

The reporting times may be added to the schedule so the cloud can coordinate the events.

## Schedule Schema

Below is an example schema represented in JSON for clarity, then MsgPack for accuracy.

* `ps` - **required** - The unix time the process started running.  This should not change except when the process is restarted.
* `id` - **required** - The device-id running this instance of Aker.
* `rows` - **required** - The array of rows of data.  The default is to provide the last 3 data points (typically 24h worth of data).
* `ts` - **required** - The unix time of the data set in UTC time.
* `off` - **required** - The offset in seconds based on the schedule specified timezone.
* `dbc` - **required** - The device block count is the number of device ids that have been blocked since the program started.
* `wtc` - **required** - The window transition count is the number of times a transition between defined blocking windows has been encountered since the program started.
* `ssc` - **required** - The schedule set count is the number of times a schedule has been set since the program started.
* `md5` - **required** - The md5 check failure count is the number of times the md5 did not match the file since the program started.
* `tz` - **required** - The timezone string is the most recently specified timezone from the schedule in effect.

```
{
    "ps": 1622763073,
    "id": "mac:112233445566",
    "rows": [
        {
            "ts": 1622761073,
            "off": 28800,
            "dbc": 5312,
            "wtc": 204,
            "ssc": 3,
            "md5": 0,
            "tz": "PST8PDT"
        }, {
            "ts": 1622674673,
            "off": 28800,
            "dbc": 4612,
            "wtc": 123,
            "ssc": 2,
            "md5": 0,
            "tz": "PST8PDT"
        }, {
            "ts": 1622588273,
            "off": 28800,
            "dbc": 2212,
            "wtc": 54,
            "ssc": 1,
            "md5": 0,
            "tz": "PST8PDT"
        }
    ]
}
```
Hex MsgPack:
```
00000000: 82a2 7073 ce60 aeac 29a4 726f 7773 9387  ..ps.`..).rows..
00000010: a274 73ce 60b9 5e71 a36f 6666 cd70 80a3  .ts.`.^q.off.p..
00000020: 6462 63cd 14c0 a377 7463 cccc a373 7363  dbc....wtc...ssc
00000030: 03a3 6d64 3500 a274 7aa7 5053 5438 5044  ..md5..tz.PST8PD
00000040: 5487 a274 73ce 60b8 0cf1 a36f 6666 cd70  T..ts.`....off.p
00000050: 80a3 6462 63cd 1204 a377 7463 7ba3 7373  ..dbc....wtc{.ss
00000060: 6302 a36d 6435 00a2 747a a750 5354 3850  c..md5..tz.PST8P
00000070: 4454 87a2 7473 ce60 b6bb 71a3 6f66 66cd  DT..ts.`..q.off.
00000080: 7080 a364 6263 cd08 a4a3 7774 6336 a373  p..dbc....wtc6.s
00000090: 7363 01a3 6d64 3500 a274 7aa7 5053 5438  sc..md5..tz.PST8
000000a0: 5044 54                                  PDT
```

**Comment by shilpa24balaji** [comment]
@schmidtw ,
I had few questions on this issue:
1. Could you please explain this metric in more detail or with an example "the count of the number of transitions between different blocking windows"
2. For "the time the process started" is it the Aker process start time that you are looking for?
3. All these metrics, should it be persisted across reboots and the count updated? Or are you looking for only metrics for every device for each reboot?
4. These metrics needs to be sent as WRP event with JSON payload?

**Comment by schmidtw** [comment]
Sure.

1. The idea is to count the number of times that a window either starts or ends (the blocked device list changes) to help show that the transitions are happening.
2. Yes.
3. These should not persist a reboot or restart, just store them in program memory.
4. I plan for the above to be a msgpack based payload, sent via WRP.

**Comment by shilpa24balaji** [comment]
Thanks @schmidtw 
How frequent should these events be sent?

**Comment by schmidtw** [comment]
We'll set the default to something slow like once a day.

**Comment by guruchandru** [comment]
@schmidtw  The DeviceBlockCount or dbc mentioned,  is it like unique mac id that has been blocked since the aker service is started or just unique number of macs that are blocked for the same period in a schedule? If in 1st schedule 5 macs are blocked which are unique to that particular schedule and in 2nd schedule if 5 same macs used in 1st schedule are blocked they are unique to that schedule ... so the total count will be 10, is this correct? Or should we count only the unique macs in these both schedule i.e. 5?

**Comment by schmidtw** [comment]
In your example the total would be 10 since 5 were blocked, then 5 were unblocked.

**Comment by guruchandru** [comment]
Thanks @schmidtw . Will continue with that approach

**Comment by schmidtw** [comment]
Added with #177 .
